# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read


jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.10', '3.11', '3.12' ]
        networkx-version: [ '3.2', '3.3' ]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }} and NetworkX ${{ matrix.networkx-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mock numpy scipy

    - name: Install networkx==${{ matrix.networkx-version }}
      run: |
        pip install networkx==${{ matrix.networkx-version }}

    - name: Install networkx-viewer
      run: |
        python setup.py install

    - name: Runt tests
      run: |
        xvfb-run --auto-servernum --server-args="-screen 0 1024x768x24" python ./networkx_viewer/tests.py
